### PR TITLE
Bump version to 0.4.7

### PR DESCRIPTION
**Pull request by Benew**
For projects that need the latest patches

### CODE REVIEW

**Comment by armellarcier** [comment]
Hi! Thanks for the merge. Can you publish 0.4.7 on npm please?

**Comment by armellarcier** [comment]
@lykmapipo Sorry to bother you but I'm gonna have to rely on the latest github in my app's dependencies on production unless the npm package is published. That makes me feel bad which is why I'm being a pain about it... ;)

**Comment by lykmapipo** [comment]
@Benew Sorry for delays. Its done.

**Comment by armellarcier** [comment]
@lykmapipo thanks a TON!

**Pull request merged**
