### PR TITLE
require lodash

### PR DESCRIPTION
**Pull request by isery**
this fixes the issue that lodash is not in your projects package.json and also in production we run sails www and that won't go through if lodash is global. Besides that its not the beste style to have global variables.

### CODE REVIEW

**Comment by lykmapipo** [comment]
@isery what about requiring internal sails `lodash` than installing on our own?

Dont you think we will maintain compactibility with sails dependencies?

**Comment by lykmapipo** [comment]
@isery what about `sails.util._`

**Comment by lykmapipo** [comment]
@isery What about using [parent-require](https://github.com/jaredhanson/node-parent-require)

```js
var prequire = require('parent-require');
var async = prequire('async');
var lodash = prequire('lodash');
```

In that fashion we will be requiring packages from `sails`

How about that?.

**Comment by isery** [comment]
I like the idea of sails.util._ and I changed the PR but travis does not run through? On my local machine all tests passed. Any Idea?

**Comment by lykmapipo** [comment]
@isery Am on it

**Comment by isery** [comment]
any news on this one?

**Comment by lykmapipo** [comment]
@isery I have been in a tight schedule. Hopely next week I will have time on this.

**Pull request merged**
