### PR TITLE
Fix errors with associations

### PR DESCRIPTION
**Pull request by VMBindraban**
#18

Prevent overriding `error.Errors` when validation returns an empty object.

### CODE REVIEW

**Comment by lykmapipo** [comment]
@VMBindraban 

Am on it.

Thanks

**Comment by VMBindraban** [comment]
@lykmapipo Any updates?

**Comment by VMBindraban** [comment]
@lykmapipo Any updates?

**Comment by lykmapipo** [comment]
@VMBindraban 

I have been occupied recently...I will work on it late this week.

Thanks.

**Pull request merged**
